# Generated by Django 3.2.13 on 2022-05-21 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tracker', '0002_auto_20220518_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='start_time',
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('day', models.CharField(choices=[('Monday', 'Mon'), ('Tuesday', 'Tue'), ('Wednesday', 'Wed'), ('Thursday', 'Thu'), ('Friday', 'Fri')], default='Monday', max_length=20)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance_tracker.classes')),
            ],
        ),
    ]
