# Generated by Django 3.2.13 on 2022-05-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tracker', '0006_auto_20220521_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('Monday', 'Mon'), ('Tuesday', 'Tue'), ('Wednesday', 'Wed'), ('Thursday', 'Thu'), ('Friday', 'Fri'), ('Saturday', 'Sat'), ('Sunday', 'Sun')], default='Monday', max_length=20),
        ),
    ]
