# Generated by Django 3.2.13 on 2022-05-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tracker', '0007_alter_timetable_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='departement',
            field=models.CharField(choices=[('ECE', 'Ece'), ('CSE', 'Cse')], default='CSE', max_length=20),
        ),
    ]
